CREATE TABLE IF NOT EXISTS admin_users(
	id serial PRIMARY KEY,
	name VARCHAR (50) UNIQUE NOT NULL,
	email VARCHAR (255) UNIQUE NOT NULL,
	password VARCHAR (255) UNIQUE NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at DATETIME DEFAULT NULL
)